    name: Update Navigation JSON

    on:
      push:
        branches:
          - main
        paths:
          - 'essentials/**.md'
          - 'essentials/**.mdx'
          - 'api-reference/**.md'
          - 'api-reference/**.mdx'

    jobs:
      update_nav:
        # if 条件式のクォーテーションを修正
        if: "!contains(github.event.head_commit.message, '[skip ci]')"

        runs-on: ubuntu-latest

        permissions:
          contents: write

        steps:
          - name: Checkout repository
            uses: actions/checkout@v4
            with:
              token: ${{ secrets.GITHUB_TOKEN }}

          - name: Set up Node.js
            uses: actions/setup-node@v4
            with:
              node-version: '18'

          - name: Generate navigation data
            run: node scripts/generate-nav.js

          - name: Configure Git
            run: |
              git config --global user.name 'github-actions[bot]'
              git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          - name: Check for changes in docs.json
            id: git_diff
            run: |
              git diff --quiet docs.json || echo "changed=true" >> $GITHUB_OUTPUT

          - name: Commit and push changes
            if: steps.git_diff.outputs.changed == 'true'
            run: |
              git add docs.json
              git commit -m "chore: Auto-update navigation [skip ci]"
              git push
